services:
  bytebase:
    image: bytebase/bytebase:3.7.1
    container_name: bytebase
    init: true
    ports:
      - "8080:8080"
    volumes:
      - ~/.bytebase/data:/var/opt/bytebase
    restart: unless-stopped
